// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChjA8Y08Jl0ovKUQD9nNpCWvi7weGt9hw',
    appId: '1:358531910237:web:fbb4d19d282950d0955bb4',
    messagingSenderId: '358531910237',
    projectId: 'carrentalmanager-37aa2',
    authDomain: 'carrentalmanager-37aa2.firebaseapp.com',
    storageBucket: 'carrentalmanager-37aa2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChJA8Y08Jl0ovKUDQ9hNpCWvi7weGt9hw',
    appId: '1:358531910237:android:c10e5ab12e0fe91e955bb4',
    messagingSenderId: '358531910237',
    projectId: 'carrentalmanager-37aa2',
    storageBucket: 'carrentalmanager-37aa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJA8Y08Jl0ovKUDQ9hNpCWvi7weGt9hw',
    appId: '1:358531910237:ios:0cdeef1b34286535955bb4',
    messagingSenderId: '358531910237',
    projectId: 'carrentalmanager-37aa2',
    storageBucket: 'carrentalmanager-37aa2.firebasestorage.app',
    iosBundleId: 'com.example.carRentalManager',
  );
}
